# Generated by Django 3.2.3 on 2021-05-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date_added',)},
        ),
    ]
