# Generated by Django 3.2.3 on 2021-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210530_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='product.Ingredient'),
        ),
    ]
