# Generated by Django 3.2.3 on 2021-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210530_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='product.Ingredient'),
        ),
    ]
