# Generated by Django 3.2.3 on 2021-05-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210531_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
