# Generated by Django 3.2.3 on 2021-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210531_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default='awesome', max_length=500),
        ),
    ]
